import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  bool isEn = true;


  Map<String, Object> textsJp = {
    "start":"始めましょう",
    "drawer_name":"クッキングアップ",
    "drawer_item1": "お食事",
    "drawer_item2": "フィルタ",
    "drawer_item3": "テーマ",
    "drawer_switch_title": "言語を選択してください",
    "drawer_switch_item1": "英語",
    "drawer_switch_item2": "日本語",
    "theme_appBar_title": "あなたのテーマ",
    "theme_screen_title": "テーマの選択を調整する",
    "theme_mode_title": "テーマモードを選択してください",
    "System_default_theme": "システムのデフォルトテーマ",
    "light_theme": "ライトテーマ",
    "dark_theme": "ダークテーマ",
    "primary": "原色を選択してください",
    "accent": "アクセントの色を選択してください",
    "filters_appBar_title": "あなたのフィルター",
    "filters_screen_title": "食事の選択を調整する",
    "Gluten-free": "無グルテン",
    "Gluten-free-sub": "無グルテンの食事だけです。",
    "Lactose-free": "乳糖フリー",
    "Lactose-free_sub": "乳糖フリーの食事だけです。",
    "Vegetarian": "ベジタリアン",
    "Vegetarian-sub": "ベジタリアンの食事だけです",
    "Vegan": "ビーガン",
    "Vegan-sub": "ビーガンの食事だけです",
    "categories": "カテゴリ",
    "your_favorites": "お気に入り",
    "cat-c1": "イタリア",
    "cat-c2": "はやく簡単",
    "cat-c3": "ハンバーガー",
    "cat-c4": "ドイツ",
    "cat-c5": "ライトとラブリー",
    "cat-c6": "エキゾチック",
    "cat-c7": "朝食",
    "cat-c8": "アジア",
    "cat-c9": "フランス",
    "cat-c10": "夏",
    "Complexity.Simple": "シンプル",
    "Complexity.Challenging": "挑戦",
    "Complexity.Hard": "難しい",
    "Affordability.Affordable": "غير مكلفة",
    "Affordability.Pricey": "مكلفة",
    "Affordability.Luxurious": "باهضة الثمن",
    "min": "分",
    "min2": "分",
    "meal-m1": "トマトソースのスパゲッティ",
    "meal-m2": "ハワイ風トースト",
    "meal-m3": "クラシックハンバーガー",
    "meal-m4": "شريحة وينر",
    "meal-m5": "スモークサーモンのサラダ",
    "meal-m6": "おいしいオレンジムース",
    "meal-m7": "パンケーキ",
    "meal-m8": "クリーミーインディアンチキンカレー",
    "meal-m9": "チョコレートスフレ",
    "meal-m10": "チェリートマトのアスパラガスサラダ",
    "Ingredients": "材料",
    "Steps": "ステップス",
    "favorites_text":
        "お気に入りはまだありません-追加してください",
    "ingredients-m1": [
      "4 トマト",
      "1 オリーブオイル大さじ",
      "1 玉ねぎ",
      "250　スパゲッティ",
      "スパイス",
      "チーズ（オプション）",
    ],
    "ingredients-m2": [
      "1スライス白パン",
      "1スライスハム",
      "1スライスパイナップル",
      "1-2スライスのチーズ",
      "バター",
    ],
    "ingredients-m3": [
      "3300g牛ハック",
      "1トマト",
      "きゅうり1個",
      "1玉ねぎ",
      "ケチャップ",
      "2バーガーバンズ",
    ],
    "ingredients-m4": [
      "子牛のコートレット8個",
      '4個の卵',
      "200gパン粉",
      "100g小麦粉",
      "300mlバター",
      "100g植物油",
      '塩',
      'レモンの輪切り',
    ],
    "ingredients-m5": [
      'ルッコラ',
      "子羊のレタス",
      'パセリ',
      'フェンネル',
      "スモークサーモン200g",
      'マスタード',
      'バルサミコ酢',
      'オリーブオイル ',
      '塩とコショウ ',
    ],
    "ingredients-m6": [
      "4ゼラチン4枚",
      "150mlオレンジジュースل",
      "80g砂糖",
      "300gヨーグルト",
      "200gクリーム",
      "オレンジの皮",
    ],
    "ingredients-m7": [
      "11/2カップ中力粉",
      "31/2小さじベーキングパウダー",
      '小さじ1塩',
      "大さじ1杯の白砂糖",
      "11/4カップミルク",
      '1個の卵',
      "大さじ3バター、溶かした",
    ],
    "ingredients-m8": [
      "4鶏の胸肉",
      "1玉ねぎ",
      "にんにく2片",
      "生姜1個",
      "大さじ4アーモンド",
      "1小さじ1カイエンペッパー",
      "500mlココナッツミルク",
    ],
    "ingredients-m9": [
      "小さじ1杯の溶かしたバター",
      "大さじ2杯の白砂糖",
      "2オンス70％ダークチョコレート、バラバラに",
      "大さじ1バター",
      "大さじ1杯の中力粉",
      "41/3大さじ冷たいミルク",
      "1ピンチソルト",
      "1ピンチカイエンペッパー",
      "1個の大きな卵黄",
      "2個の大きな卵白",
      "1ピンチクリームターター",
      "大さじ1杯の白砂糖",
    ],
    "ingredients-m10": [
      "白と緑のアスパラガス",
      "30g松の実",
      "ミニトマト300g",
      'サラダ',
      "塩、コショウ、オリーブオイル",
    ],
    "steps-m1": [
      "トマトと玉ねぎを細かく切る",
      "水を沸騰させます。沸騰したら塩を加えます.",
      " スパゲッティを沸騰したお湯に入れます-それらは約10〜12分で完了する必要があります。",
      "その間に、オリーブオイルを温め、カットオニオンを加えます",
      " 2分後、トマト片、塩、コショウ、その他のスパイスを加えます",
      "スパゲッティができたらソースが出来上がります。",
      "完成した料理の上にチーズを自由に追加してください.",
    ],
    "steps-m2": [
      "白パンの片面にバターを塗る",
      "白パンにハム、パイナップル、チーズを重ねる",
      "トーストを200°Cのオーブンで約10分間焼きますة",
    ],
    "steps-m3": [
      "フォーム2パティ",
      "cのパテを炒めます。片側4分",
      "cのパンをすばやく炒めます。片側1分",
      "ケチャップ入りお団子",
      "トマト、きゅうり、玉ねぎを添えたハンバーガー",
    ],
    "steps-m4": [
      "子牛肉を約2〜4mmに柔らかくし、両側を塩漬けにします.",
      "平板上で、フォークで卵を軽くかき混ぜます。",
      "カツレツを小麦粉で軽くコーティングし、次に卵に浸し、最後にパン粉でコーティングします。",
      "  سخني الزبدة والزيت في مقلاة كبيرة 大きな鍋でバターと油を熱し（脂肪が非常に熱くなるのを待ちます）、両側が黄金色になるまでシュニッツェルを炒めます",
      "シュニッツェルが油で囲まれ、パン粉が「ふわふわ」になるように、定期的に鍋を投げてくださいا",
      "キッチンペーパーを取り除き、水気を切る。残りの油でパセリを炒め、水気を切る",
      "シュニッツェルを温めたプレートに置き、パセリとレモンのスライスを添えて提供します。",
    ],
    "steps-m5": [
      "サラダとハーブを洗ってカットする",
      "鮭をさいの目に切る",
      "マスタード、酢、オリーブオイルをデザートに加工する",
      "サラダを準備する",
      "サーモンキューブとドレッシングを追加する",
    ],
    "steps-m6": [
      "ゼラチンを鍋に溶かす",
      " オレンジジュースと砂糖を加える",
      "ストーブから鍋を取り出して",
      "ヨーグルト大さじ2を追加",
      " 残りのヨーグルトの下でゼラチンをかき混ぜる",
      "冷蔵庫ですべてを冷やす",
      "クリームを泡立てて、オレンジ色の塊の下に持ち上げます",
      "少なくとも4時間再び冷やす",
      "オレンジの皮を添えて",
    ],
    "steps-m7": [
      "大きなボウルで、小麦粉、ベーキングパウダー、塩、砂糖を一緒にふるいにかけます。",
      "中央に井戸を作り、ミルク、卵、溶かしたバターを注ぎます。滑らかになるまで混ぜる。",
      "軽く油を塗ったグリドルまたはフライパンを中火にかけます。",
      "各パンケーキに約1/4カップを使用して、バッターをグリドルに注ぐかすくい取ります。両面が茶色で、熱くなります。",
    ],
    "steps-m8": [
      "鶏の胸肉をスライスして炒める",
      "玉ねぎ、にんにく、生姜をペースト状に加工し、すべてを炒める",
      "スパイスを加えて炒めます",
      " 鶏の胸肉+ 250mlの水を加え、すべてを10分間調理します",
      " ココナッツミルクを加える",
      "ご飯と一緒に召し上がれ",
    ],
    "steps-m9": [
      "オーブンを190°Cに予熱します。縁のある天板にパーチメント紙を並べます",
      '小さじ1杯の溶かしたバターで2つのラメキンの底と側面を軽く磨きます。底と側面を縁までカバーします ',
      "ラメキンに大さじ1の白砂糖を追加します。砂糖がすべての表面を覆うまでラメキンを回転させます",
      "チョコレート片を金属製のミキシングボウルに入れます。",
      "ボウルを約3カップのお湯の鍋に弱火で置きます。",
      "中火でフライパンに大さじ1のバターを溶かします。小麦粉をまぶします。小麦粉がバターに組み込まれ、混合物が濃くなるまで泡だて器で混ぜます",
      "混合物が滑らかになり、濃くなるまで冷たいミルクで泡だて器で泡立てます。溶かしたチョコレートを入れたボウルに混合物を移します",
      "塩とカイエンペッパーを追加します。よく混ぜます。卵黄を加えて混ぜ合わせます",
      "卵白を泡立てる間、チョコレートを暖かく保つために、ボウルを熱い（煮ていない）水の上に置いておきます。",
      "卵白2個をミキシングボウルに入れます。歯石のクリームを追加します。混合物が濃くなり始め、泡立て器からの霧雨が混合物に消える前に約1秒間表面にとどまるまで、泡だて器で泡立てます",
      "砂糖の1/3を加えて泡だて器で混ぜます。もう少し砂糖を15秒ほど泡だて器で入れます。",
      "残りの砂糖を泡だて器で混ぜます。混合物がシェービングクリームとほぼ同じくらい濃くなり、柔らかいピークを保持するまで、3〜5分泡だて器を続けます",
      "卵白の半分弱をチョコレートに移します。",
      "卵白がチョコレートに完全に組み込まれるまで混ぜます。",
      "残りの卵白を追加します。ヘラでチョコレートにそっと折り、下から持ち上げて折ります",
      "'卵白が消えたら混合をやめます。準備した2つのラメキンに混合物を分けます。用意した天板にラメキンをのせます ",
      "スカッフルが膨らみ、リムの上部から浮き上がるまで、予熱したオーブンで12〜15分焼きます。",
    ],
    "steps-m10": [
      "アスパラガスを洗い、皮をむき、切る",
      "塩水で調理する",
      "アスパラガスの塩とコショウ",
      "松の実を焙煎",
      "トマトを半分にする",
      "アスパラガス、サラダ、ドレッシングを混ぜる",
      "バゲットで奉仕する",
    ],
  };
  Map<String, Object> textsEn = {
    "start": "GET STARTED",
    "drawer_name": "Cooking Up!",
    "drawer_item1": "Meal",
    "drawer_item2": "Filters",
    "drawer_item3": "Themes",
    "drawer_switch_title": "Choose your language.",
    "drawer_switch_item1": "English",
    "drawer_switch_item2": "Japanese",
    "theme_appBar_title": "Your Themes",
    "theme_screen_title": "Adjust your themes selection.",
    "theme_mode_title": "Choose your Theme Mode",
    "System_default_theme": "System Default Theme",
    "light_theme": "Light Theme",
    "dark_theme": "Dark Theme",
    "primary": "Choose your primary color",
    "accent": "Choose your accent color",
    "filters_appBar_title": "Your Filters",
    "filters_screen_title": "Adjust your meal selection.",
    "Gluten-free": "Gluten-free",
    "Gluten-free-sub": "Only include gluten-free meals.",
    "Lactose-free": "Lactose-free",
    "Lactose-free_sub": "Only include Lactose-free meals.",
    "Vegetarian": "Vegetarian",
    "Vegetarian-sub": "Only include vegetarian meals.",
    "Vegan": "Vegan",
    "Vegan-sub": "Only include Vegan meals.",
    "categories": "Categories",
    "your_favorites": "Your Favorites",
    "cat-c1": "Italian",
    "cat-c2": "Quick & Easy",
    "cat-c3": "Hamburgers",
    "cat-c4": "German",
    "cat-c5": "Light & Lovely",
    "cat-c6": "Exotic",
    "cat-c7": "Breakfast",
    "cat-c8": "Asian",
    "cat-c9": "French",
    "cat-c10": "Summer",
    "Complexity.Simple": "Simple",
    "Complexity.Challenging": "Challenging",
    "Complexity.Hard": "Hard",
    "Affordability.Affordable": "Affordable",
    "Affordability.Pricey": "Pricey",
    "Affordability.Luxurious": "Luxurious",
    "min": "min",
    "min2": "min",
    "meal-m1": "Spaghetti with Tomato Sauce",
    "meal-m2": "Toast Hawaii",
    "meal-m3": "Classic Hamburger",
    "meal-m4": "Wiener Schnitzel",
    "meal-m5": "Salad with Smoked Salmon",
    "meal-m6": "Delicious Orange Mousse",
    "meal-m7": "Pancakes",
    "meal-m8": "Creamy Indian Chicken Curry",
    "meal-m9": "Chocolate Souffle",
    "meal-m10": "Asparagus Salad with Cherry Tomatoes",
    "Ingredients": "Ingredients",
    "Steps": "Steps",
    "favorites_text": "You have no favorites yet - start adding some!",
    "ingredients-m1": [
      '4 Tomatoes',
      '1 Tablespoon of Olive Oil',
      '1 Onion',
      '250g Spaghetti',
      'Spices',
      'Cheese (optional)'
    ],
    "ingredients-m2": [
      '1 Slice White Bread',
      '1 Slice Ham',
      '1 Slice Pineapple',
      '1-2 Slices of Cheese',
      'Butter'
    ],
    "ingredients-m3": [
      '300g Cattle Hack',
      '1 Tomato',
      '1 Cucumber',
      '1 Onion',
      'Ketchup',
      '2 Burger Buns'
    ],
    "ingredients-m4": [
      '8 Veal Cutlets',
      '4 Eggs',
      '200g Bread Crumbs',
      '100g Flour',
      '300ml Butter',
      '100g Vegetable Oil',
      'Salt',
      'Lemon Slices'
    ],
    "ingredients-m5": [
      'Arugula',
      'Lamb\'s Lettuce',
      'Parsley',
      'Fennel',
      '200g Smoked Salmon',
      'Mustard',
      'Balsamic Vinegar',
      'Olive Oil',
      'Salt and Pepper'
    ],
    "ingredients-m6": [
      '4 Sheets of Gelatine',
      '150ml Orange Juice',
      '80g Sugar',
      '300g Yoghurt',
      '200g Cream',
      'Orange Peel',
    ],
    "ingredients-m7": [
      '1 1/2 Cups all-purpose Flour',
      '3 1/2 Teaspoons Baking Powder',
      '1 Teaspoon Salt',
      '1 Tablespoon White Sugar',
      '1 1/4 cups Milk',
      '1 Egg',
      '3 Tablespoons Butter, melted',
    ],
    "ingredients-m8": [
      '4 Chicken Breasts',
      '1 Onion',
      '2 Cloves of Garlic',
      '1 Piece of Ginger',
      '4 Tablespoons Almonds',
      '1 Teaspoon Cayenne Pepper',
      '500ml Coconut Milk',
    ],
    "ingredients-m9": [
      '1 Teaspoon melted Butter',
      '2 Tablespoons white Sugar',
      '2 Ounces 70% dark Chocolate, broken into pieces',
      '1 Tablespoon Butter',
      '1 Tablespoon all-purpose Flour',
      '4 1/3 tablespoons cold Milk',
      '1 Pinch Salt',
      '1 Pinch Cayenne Pepper',
      '1 Large Egg Yolk',
      '2 Large Egg Whites',
      '1 Pinch Cream of Tartar',
      '1 Tablespoon white Sugar',
    ],
    "ingredients-m10": [
      'White and Green Asparagus',
      '30g Pine Nuts',
      '300g Cherry Tomatoes',
      'Salad',
      'Salt, Pepper and Olive Oil'
    ],
    "steps-m1": [
      'Cut the tomatoes and the onion into small pieces.',
      'Boil some water - add salt to it once it boils.',
      'Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.',
      'In the meantime, heaten up some olive oil and add the cut onion.',
      'After 2 minutes, add the tomato pieces, salt, pepper and your other spices.',
      'The sauce will be done once the spaghetti are.',
      'Feel free to add some cheese on top of the finished dish.'
    ],
    "steps-m2": [
      'Butter one side of the white bread',
      'Layer ham, the pineapple and cheese on the white bread',
      'Bake the toast for round about 10 minutes in the oven at 200°C'
    ],
    "steps-m3": [
      'Form 2 patties',
      'Fry the patties for c. 4 minutes on each side',
      'Quickly fry the buns for c. 1 minute on each side',
      'Bruch buns with ketchup',
      'Serve burger with tomato, cucumber and onion'
    ],
    "steps-m4": [
      'Tenderize the veal to about 2–4mm, and salt on both sides.',
      'On a flat plate, stir the eggs briefly with a fork.',
      'Lightly coat the cutlets in flour then dip into the egg, and finally, coat in breadcrumbs.',
      'Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until golden brown on both sides.',
      'Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the crumbing becomes ‘fluffy’.',
      'Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.',
      'Place the schnitzels on awarmed plate and serve garnishedwith parsley and slices of lemon.'
    ],
    "steps-m5": [
      'Wash and cut salad and herbs',
      'Dice the salmon',
      'Process mustard, vinegar and olive oil into a dessing',
      'Prepare the salad',
      'Add salmon cubes and dressing'
    ],
    "steps-m6": [
      'Dissolve gelatine in pot',
      'Add orange juice and sugar',
      'Take pot off the stove',
      'Add 2 tablespoons of yoghurt',
      'Stir gelatin under remaining yoghurt',
      'Cool everything down in the refrigerator',
      'Whip the cream and lift it under die orange mass',
      'Cool down again for at least 4 hours',
      'Serve with orange peel',
    ],
    "steps-m7": [
      'In a large bowl, sift together the flour, baking powder, salt and sugar.',
      'Make a well in the center and pour in the milk, egg and melted butter; mix until smooth.',
      'Heat a lightly oiled griddle or frying pan over medium high heat.',
      'Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'
    ],
    "steps-m8": [
      'Slice and fry the chicken breast',
      'Process onion, garlic and ginger into paste and sauté everything',
      'Add spices and stir fry',
      'Add chicken breast + 250ml of water and cook everything for 10 minutes',
      'Add coconut milk',
      'Serve with rice'
    ],
    "steps-m9": [
      'Preheat oven to 190°C. Line a rimmed baking sheet with parchment paper.',
      'Brush bottom and sides of 2 ramekins lightly with 1 teaspoon melted butter; cover bottom and sides right up to the rim.',
      'Add 1 tablespoon white sugar to ramekins. Rotate ramekins until sugar coats all surfaces.',
      'Place chocolate pieces in a metal mixing bowl.',
      'Place bowl over a pan of about 3 cups hot water over low heat.',
      'Melt 1 tablespoon butter in a skillet over medium heat. Sprinkle in flour. Whisk until flour is incorporated into butter and mixture thickens.',
      'Whisk in cold milk until mixture becomes smooth and thickens. Transfer mixture to bowl with melted chocolate.',
      'Add salt and cayenne pepper. Mix together thoroughly. Add egg yolk and mix to combine.',
      'Leave bowl above the hot (not simmering) water to keep chocolate warm while you whip the egg whites.',
      'Place 2 egg whites in a mixing bowl; add cream of tartar. Whisk until mixture begins to thicken and a drizzle from the whisk stays on the surface about 1 second before disappearing into the mix.',
      'Add 1/3 of sugar and whisk in. Whisk in a bit more sugar about 15 seconds.',
      'whisk in the rest of the sugar. Continue whisking until mixture is about as thick as shaving cream and holds soft peaks, 3 to 5 minutes.',
      'Transfer a little less than half of egg whites to chocolate.',
      'Mix until egg whites are thoroughly incorporated into the chocolate.',
      'Add the rest of the egg whites; gently fold into the chocolate with a spatula, lifting from the bottom and folding over.',
      'Stop mixing after the egg white disappears. Divide mixture between 2 prepared ramekins. Place ramekins on prepared baking sheet.',
      'Bake in preheated oven until scuffles are puffed and have risen above the top of the rims, 12 to 15 minutes.',
    ],
    "steps-m10": [
      'Wash, peel and cut the asparagus',
      'Cook in salted water',
      'Salt and pepper the asparagus',
      'Roast the pine nuts',
      'Halve the tomatoes',
      'Mix with asparagus, salad and dressing',
      'Serve with Baguette'
    ],
  };

  changeLan(bool lan) async{
    isEn = lan;
    notifyListeners();
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool("isEn", isEn);
  }

  getLan() async{
    SharedPreferences prefs = await SharedPreferences.getInstance();
    isEn = prefs.getBool("isEn")?? true;
    notifyListeners();
  }

  Object getTexts(String txt) {
    if (isEn == true) return textsEn[txt]!;
    return textsJp[txt]!;
  }
}
